package exception;

public class Exception {
	public static int division(int a,int b)throws ArithmeticException {
		return a/b;
	}
	public static void main(String[] args) {
		try {
			int e=division(5,0);
			
		} catch(ArithmeticException ae) {
			System.out.println("Division is not possible by zero "+ae);
		} finally {
			System.out.println("Rest of the code is excecuted");
		}
	}

}
